/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_external_VLFeat */

#ifndef _Included_utils_external_VLFeat
#define _Included_utils_external_VLFeat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_external_VLFeat
 * Method:    getSIFTs
 * Signature: (IIIIII[F[D[D[D)[S
 */
JNIEXPORT jshortArray JNICALL Java_utils_external_VLFeat_getSIFTs
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jfloatArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
